name: "cspell-action"
description: "Spell Checker for Code"
author: "Street Side Software <info@streetsidesoftware.nl>"
inputs:
  github_token:
    description: >
      Personal access token (PAT) used to fetch the repository commits. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  files:
    description: >
      Define glob patterns to filter the files to be checked. Use a new line between patterns to define multiple patterns.
      The default is to check ALL files that were changed in in the pull_request or push.
      Note: `ignorePaths` defined in cspell.json still apply.
runs:
  using: "node12"
  main: "./action/main.js"
branding:
  icon: "code"
  color: "green"
