name: 'cspell-action'
description: 'Spell check changed files.'
author: 'Street Side Software <info@streetsidesoftware.nl>'
inputs:
  milliseconds:
    description: 'Amount of time to wait.'
    default: '500'
runs:
  using: 'node12'
  main: './action'
