name: 'cspell-action'
description: 'Spell check changed files.'
author: 'Street Side Software <info@streetsidesoftware.nl>'
inputs:
    githubToken:
        description: Github Token '${{ secrets.GITHUB_TOKEN }}'
        required: true
    milliseconds:
        description: 'Amount of time to wait.'
        default: '500'
        required: true
outputs:
    time:
        description: 'Finish time.'
runs:
    using: 'node12'
    main: './action/main.js'
branding:
    icon: 'code'
    color: 'green'
