name: 'cspell-action'
description: 'Spell Checker for Code'
author: 'Street Side Software <info@streetsidesoftware.nl>'
inputs:
    github_token:
        description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
        required: true
runs:
    using: 'node12'
    main: './action/main.js'
branding:
    icon: 'code'
    color: 'green'
