---
packages:
  - action-src

onlyBuiltDependencies:
  - esbuild

minimumReleaseAge: 2880 # two days
minimumReleaseAgeExclude:
  - '@cspell/*'
  - 'cspell'
  - 'cspell-*'
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1

# cspell:dictionaries npm
