---
packages:
  - action-src

minimumReleaseAge: 2880 # two days
minimumReleaseAgeExclude:
- '@cspell/*'
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1
