name: Build Action

on:
  # push:
  #   - "!main"
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Setup Tokens
        uses: tibdex/github-app-token@v1 # cspell:ignore tibdex
        id: generate-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install
        run: |
          yarn
          yarn clean-build

      - name: Has changes
        run: |
          git --no-pager diff --compact-summary  --exit-code && echo "git_status=clean" >> $GITHUB_ENV || echo "git_status=dirty" >> $GITHUB_ENV
          git --no-pager diff --compact-summary

      - name: Echo git_status
        run: echo ${{ env.git_status }}

      - name: Commit and Push
        if: env.git_status == 'dirty'
        run: |
          git config --local user.name Jason3S
          git config --local user.email Jason3S@users.noreply.github.com
          git config --local committer.name GitHub
          git config --local committer.email noreply@github.com
          git add .
          git commit -m "Build Action"
          git push
