name: lint
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - run: node -v
      - run: npx cspell@latest "**" --dot
