name: ' 🔗 Update Dependencies Main'

on:
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: 'main'
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  update-dependencies:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: update-dependencies-${{ inputs.base || 'main' }}
      REF_BRANCH: ${{ inputs.base || 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ env.REF_BRANCH }}

      - uses: streetsidesoftware/actions/public/setup-node-pnpm@v1

      - name: Install
        run: pnpm i

      - name: Update packages
        run: |
          pnpm up -w
          pnpm up -r

      - name: Update packages Src
        run: pnpm clean-build

      - name: Git Status
        id: git-status
        uses: streetsidesoftware/actions/public/dirty@v1

      - name: Has changes
        run: |
          git --no-pager diff --compact-summary  --exit-code action && echo "PR_TYPE=ci" >> $GITHUB_ENV || echo "PR_TYPE=fix" >> $GITHUB_ENV
          git --no-pager diff --compact-summary  --exit-code && echo "git_status=clean" >> $GITHUB_ENV || echo "git_status=dirty" >> $GITHUB_ENV
          git --no-pager diff --compact-summary

      - name: Gen PR Body
        id: body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: Update Dependencies
          message: |
            **Type:** ${{ env.PR_TYPE }}
          path: >-
            package.json
            action-src/package.json
            action/package.json

      - name: Show Summary
        uses: streetsidesoftware/actions/public/summary@v1
        with:
          text: |
            ${{ steps.body.outputs.body }}

            **Status:** ${{ steps.git-status.outputs.isDirty && 'dirty' || 'clean' }}

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: '${{ env.PR_TYPE }}: Workflow Bot -- Update ALL Dependencies'
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: '${{ env.PR_TYPE }}: Workflow Bot -- Update ALL Dependencies (${{ env.REF_BRANCH }})'
          body: ${{ steps.body.outputs.body }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
