name: " 🔗 Update Dependencies Main"

on:
  workflow_dispatch:
    inputs:
      base:
        description: The Base Ref to apply the diff
        required: false
        default: "main"
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read

jobs:
  update-dependencies:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: update-dependencies-${{ inputs.base || 'main' }}
      REF_BRANCH: ${{ inputs.base || 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF_BRANCH }}

      - uses: streetsidesoftware/actions/public/setup-node-pnpm@v1

      - name: Install
        run: pnpm i

      - name: Update packages
        run: |
          pnpm up

      - name: Update packages Src
        run: pnpm clean-build

      - name: Git Status
        id: git-status
        uses: streetsidesoftware/actions/public/dirty@v1

      - name: Has changes
        run: |
          git --no-pager diff --compact-summary  --exit-code action && echo "PR_TYPE=ci" >> $GITHUB_ENV || echo "PR_TYPE=fix" >> $GITHUB_ENV
          git --no-pager diff --compact-summary  --exit-code && echo "git_status=clean" >> $GITHUB_ENV || echo "git_status=dirty" >> $GITHUB_ENV
          git --no-pager diff --compact-summary

      - name: Gen Body
        run: |
          echo 'git_body<<DIFF' >> $GITHUB_ENV
          git --no-pager diff --compact-summary >> $GITHUB_ENV
          echo 'DIFF' >> $GITHUB_ENV

      - name: Summary
        id: summary
        uses: streetsidesoftware/actions/public/output@v1
        with:
          value: |
            Type: ${{ env.PR_TYPE }}

            Status: ${{ steps.git-status.outputs.isDirty && 'dirty' || 'clean' }}
            ```
            ${{ steps.git-status.outputs.status }}
            ```

            diff:
            ```
            ${{ env.git_body }}
            ```
      - name: Show Summary
        uses: streetsidesoftware/actions/public/summary@v1
        with:
          text: ${{ steps.summary.outputs.value }}

      - name: PR
        uses: streetsidesoftware/actions/.github/actions/pr@v1
        with:
          commit-message: "${{ env.PR_TYPE }}: Workflow Bot -- Update ALL Dependencies"
          branch: ${{ env.NEW_BRANCH }}
          base: ${{ env.REF_BRANCH }}
          title: "${{ env.PR_TYPE }}: Workflow Bot -- Update ALL Dependencies (${{ env.REF_BRANCH }})"
          body: ${{ steps.summary.outputs.value }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
